steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-west2-docker.pkg.dev/bootcamp-361907/quickstart-docker-repo/bootcamp-image:tag1', '.' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'bootcampservice'
      - '--image'
      - 'us-west2-docker.pkg.dev/bootcamp-361907/quickstart-docker-repo/bootcamp-image:tag1'
      - '--region'
      - 'us-west2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'us-west2-docker.pkg.dev/bootcamp-361907/quickstart-docker-repo/bootcamp-image:tag1'